### ISSUE TITLE
Studio keep on asking for login credentials after login.

### ISSUE THREAD

**Issue by gauravdhiman** [orientechnologies/orientdb-studio#147]
This issue came up with latest 2.0 release, it was not there in 1.7.8 version.

Even after login to studio successfully it  keeps on asking the login credentials again and again. It asks for login credentials at least 7 to 8 times. If we keep on cancelling the login request, it says 401 error, but on page refresh things work as we anyhow logged in successfully earlier so session exists.

Kindly refer to below screenshot:
![image](https://cloud.githubusercontent.com/assets/5612223/4384361/5a649572-43b5-11e4-9e5e-5032843e3534.png)

**Comment by adrianblynch** [comment]
@lvca - This is happening to me on Studio 2.1 and Orient version 2.1.5. This issue is flagged as won't fix, but what is the solution? Add back a guest user with listDatabases permission?

Do all of these need to be present?

`<user resources="connect,server.listDatabases,server.dblist" password="guest" name="guest"/>`

**Comment by lvca** [comment]
these are necessary to enlist the databases.

**Comment by smolinari** [comment]
Hi,

I just did a fresh install and was also running into the problem of Studio constantly asking for htaccess credentials. I added the following line under the users element in the `orientdb-server-config.xml` file and it solved the problem.

`<user resources="connect,server.listDatabases" password="guest" name="guest"/>`

So, I'd say, this line seems to be missing in the default `orientdb-server-config.xml` file, once ODB is installed and needs to be added.

Scott

**Comment by lvca** [comment]
@smolinari the first time the server startups, the server check the existence of guest & root. If not present it creates them. After the first time the flag "isAfterFirstTime" is created in xml. Could it be the server was wrongly started the first time, the flag was set and it never checked for guest anymore on further startups?

**Comment by smolinari** [comment]
That could be. The install was through a custom built vagrant box. I'll check some more and get back on that.

Scott

**Comment by khoatran** [comment]
I've got the same issue. Even I tried with adding the line:

<user resources="connect,server.listDatabases,server.dblist" password="guest" name="guest"/>

It still doesn't work. However, I've found a workaround way to fix this. I changed above line to:

<user resources="*" password="guest" name="guest"/>
and restart the Studio. Then I can create the database successfully. 
However, I expect Studio team should fix this. I am running the Studio version on orientdb-community-2.1.7.

**Comment by StarpTech** [comment]
I've got also the same issue but only in chrome.

**Comment by smolinari** [comment]
Getting back to this thread, as I mentioned I would (but forgot). The problem I had definitely came from an incorrectly set up config, which I believe came from initially starting the server with `server.sh` instead of configuring and starting orientdb with `orientdb.sh`. The guest and root users must both be present in the `orientdb-server-config.sh`, for Studio to work properly.

Scott
