### ISSUE TITLE
Enhancement: Multiple panels in graph mode

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb-studio#293]
Neo4j supports multiple query history in graph mode. It would be nice to have it in OrientDB as well - and improved with scrollbars that Neo4j doesn't have ;) 

<img src="http://jaxenter.com/wp-content/uploads/2013/12/rik-3.jpg"/>

**Comment by lvca** [comment]
We preferred to avoid to kill the browser with too stuff: D3 could be very heavy. @maggiolo00 WDYT?

**Comment by kwoxer** [comment]
D3 force layout is not a good way. And I believe Neo4j isn't using this for the presentation view.

**Comment by santo-it** [comment]
Hi,

I believe what zifnab87 is suggesting is indeed useful. One may want to perform multiple queries and keep (some) graph panels open (for different reasons)

In *eo4j it's kind of standard to have multiple panels open. I haven't noticed serious performance issues due to this in that product, and on the other hand I did enjoy this feature during my work with it 

If this enhancement is implemented, it can be left up to users to find the best compromise between number of open graph panels and browser performance - a warning may be returned if there are too many panels open. The documentation may include a warning as well, if necessary

I noticed lack of this feature immediately coming from *eo4j

The "Browse" tab supports multiple panels already - so seems like a matter to extend this to the Graph Editor as well 

Ideally an option is implemented so that users can choose if they want a single canvas (that can be cleared just in case) as it is now, or multiple canvas 

Current Workaround: open Studio in different tabs (or browsers) and use the Graph Editor on each tab (or browser)

+1 to implement this in a future release 

Thanks,

**Comment by maggiolo00** [comment]
@santo-it 

The idea of Graph Editor is different from the Browse tab. In the graph editor
you can compose/manipulate a graph with multiple query, or relationship expansion or single remove of nodes. In this way creating custom graph representation if your data it is simpler, instead of just showing one result set in a graph. 
I think the best way if you want a graph representation of result set is to add to another tab in the Browser UI ( Table / Raw / Graph)

**Comment by santo-it** [comment]
Hi,

Thanks for your reply. Sure, can be an idea
If possible, it would be also useful to print number of returned nodes and relationships, e.g. similar to 

"Query executed in 0.205 sec. Returned 10 record(s). Limit: 20"

but with number of returned nodes and relationships

Let me know if you feel I should open another issue for this specific enhancement

Thanks!

**Comment by santo-it** [comment]
Hi @maggiolo00 ,

Just wondering: we make this new "Graph" subtab (in the "Browse" tab), read only or where you thinking to add some other features (e.g. ability to click on vertices and edges and see properties, zoom, colors, etc)? I believe understanding which feature to add is something to discuss before taking decision on whether adding this new tab or make multi-panel the graph editor (with an option that would allow users to select the strategy: 1. add results to the same panel (as it is now). 2. clear panels and reprint graph. 3. create a new panel for each new query

What is more feasible in your opinion in terms of implementation and maintenance costs?

Thanks,

**Comment by lvca** [comment]
Not relevant anymore, closing it.
