### ISSUE TITLE
Count bothE() vs Count E

### ISSUE THREAD

**Issue by WittR** [orientechnologies/orientdb-studio#369]
Hi !

I don't know if it's a bug, but can you explain me this difference ? 

Actually, I work on the beta : I test this on the previous version and there is not any difference.

![orientdbbug](https://cloud.githubusercontent.com/assets/14804697/14979305/c65fa83a-1121-11e6-897a-2e7d5be91bbb.png)

Cheers,

**Comment by luigidellaquila** [comment]
Hi @WittR 

you can have two differences here:
- edges that have both out and in pointing to 45:0
- broken edges (and I think it's your case): edges that exist as records but that are not correctly linked to vertices

Thanks

Luigi

**Comment by WittR** [comment]
Thanks for your answer ! 

What can I do for solve this problem of broken edges ? This database comes from an unique ETL processing, so I don't understand why some edges are broken ...

Cheers,

**Comment by luigidellaquila** [comment]
Hi @WittR 

first of all we should see if that's the real problem...

You can start executing there queries:

```
select from E where (out = #45:0 or in = #45:0) 
and @this not in (
    select expand(bothE()) from #45:0
)
```
For the resulting edges, you have to see if they are in the corresponding out_* or in_* field of the `#45:0` vertex.
If it's the case then there is a problem in the query engine. On the other hand, if it's not the case, you can fix the vertex manually adding the edge RID to the out_* or in_* field (simple UPDATE ... ADD)

Thanks

Luigi

**Comment by WittR** [comment]
There we are  3256 - 1 = 5818 - 2563 <=> 
There is 1 both In and Out pointing to #45:0
There are 3255 broken edges

![orientdbbug2](https://cloud.githubusercontent.com/assets/14804697/14980313/ffcb4768-1127-11e6-8764-4022a4a21c15.png)

Cheers,

**Comment by luigidellaquila** [comment]
Hi @WittR 

This is interesting...
The fix is easy, just make sure that all the edges are of the same class (or just partition them by class) and then execute a query like this:
```
UPDATE #45:0 add in_INTERACTION = (
   select from E where in = #45:0
   and @this not in (
      select expand(bothE()) from #45:0
   )
)
```

Just check that the in_INTERACTION is the right field name on the vertex 

More interesting: can you post the code that generated the problem? I think it's worth investigating if it's an issue in the engine

Thanks

Luigi

**Comment by WittR** [comment]
I will test your solution after, but i have many vertices which have this issue ... 
And again, there is not this problem on the previous version !

For the code : https://drive.google.com/file/d/0B9gbyUxiVmBmc1VyNXZNM0w0ZlU/view?usp=sharing

Cheers,

**Comment by luigidellaquila** [comment]
Hi @WittR 

I think this issue is related to some defect in the first beta, could you please try using latest snapshot?
(download available here)
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/

Anyway, the first RC should be released in short, and AFAIK it does not suffer from this kind of problems

Thanks

Luigi

**Comment by WittR** [comment]
Hi @luigidellaquila 

I tried with the latest snapshot, but the issue is not solved ... 

Cheers,

**Comment by luigidellaquila** [comment]
Hi @WittR 

I suspect that this problem is related to this issue

https://github.com/orientechnologies/orientdb/issues/5785

It was fixed yesterday with this commit

https://github.com/orientechnologies/orientdb/commit/dba9422e09ec89a7161a9182e15659c961b34525

I guess you downloaded the snapshot without this fix, could it be the case?

Thanks

Luigi

**Comment by WittR** [comment]
It's the case, I downloaded the version before. Where can I dowload this new version in order to test ?

Cheers,

**Comment by luigidellaquila** [comment]
This should contain the fix:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/orientdb-community-2.2.0-20160504.095545-53.tar.gz

as an alternative, you can build from sources on the develop branch:
```
git clone git@github.com:orientechnologies/orientdb.git
git checkout develop
mvn clean install 
```

Thanks

Luigi

**Comment by WittR** [comment]
I've just tested, the issue is not solved with this version :/ 

Cheers,

**Comment by luigidellaquila** [comment]
Ok, it must be something else then, let me check it again

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @WittR 

we reproduced the problem locally, we are working to a fix

Thanks

Luigi

**Comment by WittR** [comment]
Hi ! 

Have you any news ? :)

Cheers,

**Comment by tglman** [comment]
Hi,

This is fixed and is released in the 2.2 RC.

Regards

**Comment by WittR** [comment]
Hi !

I've just tested from this release : http://orientdb.com/orientdb-labs/, and I always have this problem ... 
I also tested with orientdb-community-2.2.0-20160517.132718-93.tar.gz 

Thanks for your work :) 

Cheers,

**Comment by WittR** [comment]
Well, I forgot to update the drivers, all is okay now !

Thanks you again guys !

Cheers,
