### ISSUE TITLE
Release tags for OrientDB Studio

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb-studio#377]
It will be great to have release tags defined for Studio a long with OrientDB releases. Is this possible?

**Comment by maggiolo00** [comment]
@PhantomYdn 
now studio is deployed manually in the plugin folder on the server project of orientdb. This will be changed soon, then we can start tagging also orientdb-studio as well

**Comment by PhantomYdn** [comment]
I'm planning to embedd OrientDB Studio as widget into [Orienteer](https://github.com/OrienteerDW/Orienteer) and it will be great to have it taged. In this case Studio can be included as java dependency.

**Comment by xvik** [comment]
I'm afraid github tag will not be enough for you because you need studio delivery (the same as in plugin jar) but not just sources.

The best way I found so far is to use [studio webjar](https://github.com/webjars/orientdb-studio) ([usage](https://github.com/xvik/dropwizard-orient-server#orient-studio)). This jar is a repackaged from community delivery. 
The main problem with this approach is that its manual: I have to create issue/pull request to webjar repo and then James publish new version (manually). As a result, I didn't track bugfix studio versions (in most cases its ok - bundled studio version is the same, but sometimes studio is also fixed in bugfix releases).

It would be perfect if orient team publish studio delivery. I suggest using bower or npm for publishing (because it's very simple to do). This way node projects could also embed studio.
And java projects will use webjars, created from [bower or node package](http://www.webjars.org/).
Such webjars are not appeared automatically, but, any user could request new bower/node package version conversion (there is a button on website) and new jar will be deployed on maven central and jcenter (dependency is available immediately).

**Comment by PhantomYdn** [comment]
@xvik , thank you for raising this! That's exactly that way which I planned to use:) WebJars are awesome. Bower or npm will be perfect.

**Comment by maggiolo00** [comment]
Hi @PhantomYdn 

the first step is done. I've added a pom.xml in orientdb-studio so the build is maven friendly.
`mvn clean install ` to build studio.
The we will publish the zip on sonatype and our distribution will depend on it.

**Comment by PhantomYdn** [comment]
That's great:) I do recommend you to check WebJars out: http://www.webjars.org/ 
It will be great if your library will be published under WebJars because there are lots of 3rd party libraries for different web-frameworks which allow to plug-in WebJars. If you will have your own separate JAR for studio - it will be relatively hard for everyone to include into projects.

**Comment by xvik** [comment]
@maggiolo00 Is it possible to change zip to jar? 
As I remember, there is no difference for orient plugin system between zip and jar plugins. But there is a huge difference for embedded usage: with zip we will have to introduce additional build steps to unpack studio into our app resources, whereas jar could be used directly.

It will not be possible to publish as webjar, because webjars releases are managed by webjars organization (no way to automate releases with orient). But, if you consider publishing npm or bower package, then anyone could request webjar creation (manually, but immediate) from npm or bower package. 
Also, this way nodejs projects will also be able to embed studio (I remember such requests from the community).

**Comment by PhantomYdn** [comment]
@xvik , your statement that "It will not be possible to publish as webjar, because webjars releases are managed by webjars organization (no way to automate releases with orient). " is not 100% true. If there is NPM or bower: publishing of webjar is fully depends on availability of corresponding packages. It's semiautomated: you just need to trigger building of new webjar package when corresponding NPM/Bower is shouted out. Also there is a way to have a classic webjars mantained by corresponding OrientDB person. I do recommend to check WebJars functionality deeper.

**Comment by maggiolo00** [comment]
hi Guys our primary goal is to produce zip/jar and publish it so our distribution can depend on it and we can remove the zip in the source code of orientdb.
Then we can see other options too like webjars.

@xvik 
i think now `mvn clean install` produced the zip and the jar

**Comment by PhantomYdn** [comment]
@maggiolo00 that's great if jar is already there:) Is it published in maven central?

**Comment by maggiolo00** [comment]
@PhantomYdn 
not yet, i think we will publish it starting from 2.2.15

**Comment by maggiolo00** [comment]
hi @Guys 

we started to rollout snapshots on sonatype

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-studio/2.2.15-SNAPSHOT/

**Comment by xvik** [comment]
Unfortunately, studio jar doesn't contain studio, which force us to use zip version and add additional build steps to extract zip.

Here is how zip content could be added inside jar. 

Enable directory format for assembly:
```xml
<formats>
        <format>zip</format>
        <format>dir</format>
</formats>
```

Change assembly plugin phase from `package` to `generate-resources` (maven should preserve definition order for the same phase, so exec plugin will be called first):
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>distribution-package</id>
                        <phase>generate-resources</phase>
                        <goals>
```

And, finally, add generated assembly directory as resources directory:
```xml
<build>

        <resources>
          <resource>
            <directory>${build.directory}/${artifactId}-${version}.dir</directory>
          </resource>
        </resources>

        <plugins>
```

Now jar will contain both maven metadata and studio archive. 

I'm sure this will work, but yarn build doesn't work on my machine (tired solving it's problems.. node is too painful) so I can't check the full build cycle.

**Comment by maggiolo00** [comment]
hi @xvik 

in 2.2.x 

was missing

`<format>jar</format>`

that will produce the jar version with studio inside

**Comment by maggiolo00** [comment]
@xvik  added
https://github.com/orientechnologies/orientdb-studio/commit/b51c03b6b5ba87e7ccb3599467159372d2c7bcfb

**Comment by xvik** [comment]
Yes it will, but without maven metadata inside. 
Anyway, It's ok for me. Thank you!

**Comment by maggiolo00** [comment]
@xvik 

can we add some config in order to add maven metadata?

I've found this

https://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-repositories.html

can be useful ?

**Comment by xvik** [comment]
It will add maven repository structure inside jar, but not maven metadata.
I searched for other options, but there seems to be no simple way to include metadata.
I posted above the best solution I come to.

I was going to use maven metadata to be able to show studio version at runtime and validate studio compatibility with orient server (the way I currently do with webjar). 
But it's not critical. If I have officially maintained studio jar I would already be happy - I was waiting 3 years for it :)

**Comment by maggiolo00** [comment]
Hi Guys 

release tags are now aligned with OrientDB and the Studio package is published in maven central.

Can we close this?

Thanks

**Comment by xvik** [comment]
I vote for closing

**Comment by lvca** [comment]
Closing
