### ISSUE TITLE
Graph Editor - Edge Colors - Support for color:{inherit:'from' | 'to'}

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#455]
Hi,

Our graph editor with a simple query (new demoDB):

![studio](https://cloud.githubusercontent.com/assets/14923389/23283941/fba53212-fa28-11e6-856a-26a97e1513de.PNG)

Would be good to be able to set some "default" for edge color. It should still be possible to configure specific colors for specific classes, but would be good to quickly set the following options for all edge classes:

color:{inherit:'from'}
or
color:{inherit:'to'}

This is similar to nodejs, where also both is supported. See the difference of the options in the following image:

![visjs](https://cloud.githubusercontent.com/assets/14923389/23284007/5c4e1e1c-fa29-11e6-83da-90016a794234.PNG)

If we have "from" by default for each edge classes, this is the result:

![all_from_defaults](https://cloud.githubusercontent.com/assets/14923389/23284029/834176d6-fa29-11e6-9783-c89768b2bf5a.PNG)

and in our graph editor:

![all_from_graph_editor](https://cloud.githubusercontent.com/assets/14923389/23284103/f2249998-fa29-11e6-9c7e-4ef6e7d48216.PNG)

Compare the first image (default when doing that query) with this last image, that could be our new default. I think this second one is better

Just a small improvements that can makes things nicer. WDYT?

FYI, doc about both, to, from, etc, from visj:

![visjs_explanation](https://cloud.githubusercontent.com/assets/14923389/23284214/a0d71ec0-fa2a-11e6-88e4-9b6bd9fdf09e.PNG)

**Comment by maggiolo00** [comment]
hi @santo-it 

i think this is not easy to solve. 

From the Graph Editor prospective it's simple. 
When drawing an edges we have all info about in/out [@class], so if the color is not configured
it's easy to chose the one from in/out instead of randomly choose from a palette.

But in the Schema when displaying a color for an edge class, that could be difficult because the in/out property usually are not defined. Which color inherit in this case?

That can lead to a consistency problem between GraphEditor and Schema

**Comment by lvca** [comment]
Closing it.
