### ISSUE TITLE
Graph Editor - Edge not refreshed after edit + Edit Edge window improvements

### ISSUE THREAD

**Issue by StarCmd** [orientechnologies/orientdb-studio#464]
## Expected behavior  
Graph Studio should update in real and handle @version.

## Actual behavior  
Updating an edge orientation create a second "arrow" (reversed), while the first one stay visible.

## Steps to reproduce  

From a new database, 2 vertex and 1 edge, go to Graph, edit the edge and swap the In and Out vertex.
If you run the query again, you see 2 edges.
If you select each of them you read on the properties panel : 

rid 18:0
class E
out 10:0
in 11:0 

And 

rid 18:0
class E
out 11:0
in 10:0 

One of them is @version 2 the other @version 1

As usual clearing the canvas and execute the query erase the wrong edge. 
However , as the canvas is graphically dynamic, leaving a "phantom" edge on which you may interact lead to data corruption.

**Comment by santo-it** [comment]
Hi,

Thank you for opening this issue. I have tested with 2.2.18 on Windows

What I see with 2.2.18 is that, say we start from Node1-->Node2. After I swap In and Out and press the save button I still see an edge (and not two) but the edge has not been refreshed, because I still see it from Node1 to Node2. However, if I clear the canvas and execute the query again I see the edge from Node2 to Node1, so it seems that the update query was successfully but the edge was not refreshed correctly 

Note that when pressing "save changes", if the change is not correctly saved the dialog is closed anyway. I'd suggest we check result from server, if possible, and in case show error message (and leave the dialog open if an error was returned). To repeat try to edit the in or out from e.g. #10:0 to #10:0sssssss

Thanks,

**Comment by StarCmd** [comment]
Hi,
I upgraded to 2.2.18
Got a new wrong behavior. Should I open a new Issue ?
With a new blank db, using the graph editor, create 2 V then try to create an edge  : you can't as it mistake the class. It's a random bug, sometime i got E.

![newedge](https://cloud.githubusercontent.com/assets/27196262/24898950/e3366058-1e9e-11e7-99bc-b880c33e6cfc.png)

![newedge2](https://cloud.githubusercontent.com/assets/27196262/24898953/e5e42e66-1e9e-11e7-9c56-333a386867b0.png)

![newedge3](https://cloud.githubusercontent.com/assets/27196262/24898956/e92a9358-1e9e-11e7-811e-2afe9ce4d6c4.png)

**Comment by maggiolo00** [comment]
hi @StarCmd 

> BTW, I got a new wrong behavior. Should I open a new Issue or are they related ?
With a new blank db, using the graph editor, create 2 V then try to create an edge : you can't as it mistake the class. It's a random bug, sometime i got E.

Yes you can open another issue

Thanks

**Comment by maggiolo00** [comment]
hi @StarCmd 

The best way to swap in/out  it is with

https://orientdb.com/docs/2.2/SQL-Update-Edge.html

and not the ui. In/out fields should be disabled in update edge UI.

**Comment by maggiolo00** [comment]
Hi @StarCmd 

The problem was that the  the first one stayed visible with old values. That because by swapping in/out, the GraphEditor interpreted that change as a new Edge. 

We did remove in/out property from the edit/add edge (https://github.com/orientechnologies/orientdb/issues/7339) so this issue should not happen anymore

Thanks
